version: '3.7'

services:
  db:
    container_name: "tutorial_db"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks: 
    - default
    restart: always
    ports:
    - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "test_database"
      MYSQL_USER: "param"
      MYSQL_PASSWORD: "password"
    volumes:
    - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name: "tutorial_api"
    build:
      context: .
      dockerfile: api.Dockerfile
    ports:
    - "8080:8080"
    depends_on:
    - db
    volumes:
    - .:/app/
networks:
  default:
volumes:
  mysql_data:
